sonar.projectKey=aurify-backend_Aurify-Transaction
sonar.organization=aurify-backend
sonar.projectName=Aurify-Transaction
sonar.sources=.
sonar.exclusions=**/guidelines/**,**/mocks/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out